### ISSUE TITLE
node v6.x.x compatibility

### ISSUE THREAD

**Issue by asaskevich** [ilfroloff/ifnode#2]
ifnode@0.1.17 used in our project throws error after upgrading to the new version of ifnode:
```js
d:\app\protected\models\somemodel.js:8
var somemodel = app.Model({
               ^

TypeError: Cannot read property 'Model' of undefined
    at Object.<anonymous> (d:\app\protected\models\somemodel.js:8:16)
```
Similar error exists for controllers and components, and it seems to be incompatible with node v6 for the newest versions of ifnode

**Comment by ilfroloff** [comment]
Hello, @asaskevich 

Please, check migration proposals from `0.x` to `1.x` version of `ifnode` which described **[here](https://github.com/ilfroloff/ifnode/wiki/Migration-from-0.x-to-1.x)**. It must help to you.
